version: '3'

volumes:
  prometheus-data:
    driver: local

services:
  prometheus:
    network_mode: "host"
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./:/app/
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/app/prometheus.yaml"

  grafana:
    network_mode: "host"
    image: grafana/grafana:latest